import db, { insertOrUpdateInterruption, logScrapeRun, REAL_FB_POSTS, resolveRealFbPostUrl } from './index';
import { Interruption } from '@/types';
import { computeLiveStatus } from '../lib/status-utils';
import { reconcileAllInterruptions } from '../parser/superseder';

const THIRTY_DAY_DATA: Omit<Interruption, 'id'>[] = [
  // ==========================================
  // TODAY (Sep 5, 2026) — Active Outages
  // ==========================================
  {
    fbPostId: "post-today-1",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany/posts/1221948275920042",
    date: "2026-09-05",
    dateLabel: "Today (Sep 5)",
    timeStart: "01:30",
    timeEnd: "04:30",
    time: "1:30 AM – 4:30 AM",
    type: "emergency",
    status: "ongoing",
    statusLabel: "Active Outage",
    area: "San Roque, Tejero & Tinago",
    city: "Cebu City",
    barangays: ["San Roque", "Tejero", "Tinago"],
    streets: "M.J. Cuenco Ave, E. Aboitiz St, Bonifacio St, T. Padilla St",
    reason: "Automatic safety feeder protection tripped due to localized equipment fault. Troubleshooters currently dispatched on-site.",
    fbCaption: "EMERGENCY POWER OUTAGE ADVISORY: Please be informed of an unscheduled power interruption affecting portions of San Roque, Tejero, and Tinago, Cebu City. Automatic feeder protection was activated. Estimated restoration: 4:30 AM.",
    fbTime: "45m ago",
    isPast: false,
    outcome: "ongoing"
  },
  {
    fbPostId: "post-today-2",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany/posts/1221947812040019",
    date: "2026-09-05",
    dateLabel: "Today (Sep 5)",
    timeStart: "11:15",
    timeEnd: "17:00",
    time: "11:15 AM – 5:00 PM",
    type: "delayed",
    status: "delayed",
    statusLabel: "Delayed Start",
    area: "Cadulawan & Linao",
    city: "Talisay City",
    barangays: ["Cadulawan", "Linao"],
    streets: "Amazona Street, Ottawa Street, portion of Cebu South Road",
    reason: "Work commenced at 11:15 AM instead of 9:00 AM due to site access obstacles. Power will be normalized by 5:00 PM.",
    fbCaption: "ADVISORY UPDATE: The scheduled system improvement work in Cadulawan & Linao, Talisay City has started at 11:15 AM instead of 9:00 AM. Power is expected to be restored by 5:00 PM.",
    fbTime: "2 hours ago",
    isPast: false,
    outcome: "ongoing"
  },
  {
    fbPostId: "post-today-3",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany/posts/1221947510220011",
    date: "2026-09-05",
    dateLabel: "Today (Sep 5)",
    timeStart: "09:00",
    timeEnd: "15:30",
    time: "9:00 AM – 3:30 PM",
    type: "scheduled",
    status: "upcoming",
    statusLabel: "Scheduled",
    area: "Cansaga & Jugan",
    city: "Consolacion",
    barangays: ["Cansaga", "Jugan"],
    streets: "Cansaga Bay Coastal Access Rd, Jugan National Hwy",
    reason: "Upgrading 23kV overhead lines and installation of wildlife protective guards.",
    fbCaption: "SCHEDULED POWER INTERRUPTION: Lineworkers are conducting line protection enhancements in Consolacion covering Cansaga and Jugan from 9:00 AM to 3:30 PM today.",
    fbTime: "4 hours ago",
    isPast: false,
    outcome: "ongoing"
  },

  // ==========================================
  // UPCOMING ADVISORIES (Sep 6 to Sep 11, 2026)
  // ==========================================
  {
    fbPostId: "post-upcoming-1",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany/posts/1221946501920038",
    date: "2026-09-06",
    dateLabel: "Tomorrow (Sep 6)",
    timeStart: "08:30",
    timeEnd: "16:30",
    time: "8:30 AM – 4:30 PM",
    type: "cancelled",
    status: "cancelled",
    statusLabel: "Cancelled",
    area: "Maguikay & Casuntingan",
    city: "Mandaue City",
    barangays: ["Maguikay", "Casuntingan"],
    streets: "M.L. Quezon Ave, Country Club Village, Holy Family Rd",
    reason: "Cancelled due to bad weather conditions and safety protocol. Power supply remains ON.",
    fbCaption: "CANCELLATION ADVISORY: The scheduled maintenance previously announced for Mandaue City (Maguikay & Casuntingan) on Sep 6 will no longer push through. Power will remain uninterrupted.",
    fbTime: "5 hours ago",
    isPast: false,
    outcome: "cancelled"
  },
  {
    fbPostId: "post-upcoming-2",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany/posts/1221943204920005",
    date: "2026-09-07",
    dateLabel: "Monday (Sep 7)",
    timeStart: "08:00",
    timeEnd: "17:00",
    time: "8:00 AM – 5:00 PM",
    type: "scheduled",
    status: "upcoming",
    statusLabel: "Scheduled",
    area: "Guadalupe, Capitol Site & Kalunasan",
    city: "Cebu City",
    barangays: ["Guadalupe", "Capitol Site", "Kalunasan"],
    streets: "R. Duterte St, V. Rama Ave, Guadalupe Main Rd, Opra",
    reason: "Distribution line reconstruction and Disconnect Switch (DS) installation to increase feeder reliability.",
    fbCaption: "SCHEDULED POWER INTERRUPTION: Please plan ahead for planned service improvement on Monday, Sep 7 affecting portions of Guadalupe, Capitol Site, and Kalunasan along R. Duterte St.",
    fbTime: "1 day ago",
    isPast: false,
  },
  {
    fbPostId: "post-upcoming-3",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany/posts/1221941104920002",
    date: "2026-09-08",
    dateLabel: "Tuesday (Sep 8)",
    timeStart: "09:00",
    timeEnd: "15:00",
    time: "9:00 AM – 3:00 PM",
    type: "scheduled",
    status: "upcoming",
    statusLabel: "Scheduled",
    area: "Yati, Poblacion & Cotcot",
    city: "Liloan",
    barangays: ["Yati", "Poblacion", "Cotcot"],
    streets: "Catarman Road, National Highway portion, San Vicente Rd",
    reason: "Pole relocation and line raising for DPWH road improvement project.",
    fbCaption: "SCHEDULED POWER INTERRUPTION: Service enhancement scheduled in Liloan on Tuesday, Sep 8 from 9:00 AM to 3:00 PM affecting portions of Yati, Poblacion, and Cotcot.",
    fbTime: "1 day ago",
    isPast: false,
  },
  {
    fbPostId: "post-upcoming-4",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany/posts/1221940992300018",
    date: "2026-09-09",
    dateLabel: "Wednesday (Sep 9)",
    timeStart: "08:30",
    timeEnd: "16:00",
    time: "8:30 AM – 4:00 PM",
    type: "scheduled",
    status: "upcoming",
    statusLabel: "Scheduled",
    area: "Tayud & Tugbongan",
    city: "Consolacion",
    barangays: ["Tayud", "Tugbongan"],
    streets: "Tayud-Consolacion Rd, Bagong Silang, Tugbongan Port",
    reason: "Primary pole conversion and installation of automated vacuum reclosers.",
    fbCaption: "SCHEDULED INTERRUPTION: Upgrading lines in Tayud and Tugbongan, Consolacion on Wednesday, Sep 9. Power will be turned off temporarily to ensure lineworker safety.",
    fbTime: "2 days ago",
    isPast: false,
  },
  {
    fbPostId: "post-upcoming-5",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany/posts/1221940771800010",
    date: "2026-09-10",
    dateLabel: "Thursday (Sep 10)",
    timeStart: "09:00",
    timeEnd: "14:00",
    time: "9:00 AM – 2:00 PM",
    type: "scheduled",
    status: "upcoming",
    statusLabel: "Scheduled",
    area: "Lipata, Pakigne & Tungkil",
    city: "Minglanilla",
    barangays: ["Lipata", "Pakigne", "Tungkil"],
    streets: "Natalio Bacalso South National Hwy, Tungkil Barangay Rd",
    reason: "Tree trimming and hazardous branch clearance away from primary transmission cables.",
    fbCaption: "SCHEDULED MAINTENANCE: Vegetation management in Minglanilla covering Lipata, Pakigne, and Tungkil on Sep 10.",
    fbTime: "2 days ago",
    isPast: false,
  },
  {
    fbPostId: "post-upcoming-6",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany/posts/1221940552100015",
    date: "2026-09-11",
    dateLabel: "Friday (Sep 11)",
    timeStart: "08:00",
    timeEnd: "16:00",
    time: "8:00 AM – 4:00 PM",
    type: "scheduled",
    status: "upcoming",
    statusLabel: "Scheduled",
    area: "Colon & Tinaan",
    city: "City of Naga",
    barangays: ["Colon", "Tinaan"],
    streets: "Naga-Toledo Rd, Colon Port area, Tinaan Industrial Zone",
    reason: "Feeder load balancing and substation transformer busbar maintenance.",
    fbCaption: "SCHEDULED MAINTENANCE ADVISORY: City of Naga power maintenance scheduled for Friday, Sep 11 from 8:00 AM to 4:00 PM.",
    fbTime: "2 days ago",
    isPast: false,
  },

  // ==========================================
  // 30-DAY HISTORICAL BACKFILL (Aug 6 – Sep 4, 2026)
  // ==========================================
  {
    fbPostId: "hist-sep04",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-09-04",
    dateLabel: "Sep 4, 2026",
    timeStart: "09:00",
    timeEnd: "13:15",
    time: "9:00 AM – 1:15 PM",
    type: "scheduled",
    status: "restored",
    statusLabel: "Restored Early",
    area: "Mabolo & Kasambagan",
    city: "Cebu City",
    barangays: ["Mabolo", "Kasambagan"],
    streets: "M.J. Cuenco Ave, Persimmon Residences, Pope John Paul II Ave",
    reason: "Vegetation clearance finished ahead of time. Energized at 1:15 PM.",
    fbCaption: "RESTORATION ADVISORY: Normal power supply has been safely restored to all affected customers in Mabolo and Kasambagan ahead of schedule at 1:15 PM.",
    fbTime: "Sep 4",
    isPast: true,
    outcome: "restored"
  },
  {
    fbPostId: "hist-sep03",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-09-03",
    dateLabel: "Sep 3, 2026",
    timeStart: "08:00",
    timeEnd: "17:00",
    time: "8:00 AM – 5:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Tipolo & Subangdaku",
    city: "Mandaue City",
    barangays: ["Tipolo", "Subangdaku"],
    streets: "Hernan Cortes St, Lopez Jaena St, Wireless Substation",
    reason: "Substation transformer upgrade concluded successfully.",
    fbCaption: "MAINTENANCE COMPLETED: Scheduled system improvement work in Subangdaku & Tipolo has been completed successfully. Power normalized at 5:00 PM.",
    fbTime: "Sep 3",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-sep02",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-09-02",
    dateLabel: "Sep 2, 2026",
    timeStart: "13:00",
    timeEnd: "16:00",
    time: "1:00 PM – 4:00 PM",
    type: "cancelled",
    status: "cancelled",
    statusLabel: "Cancelled",
    area: "Lahug & Apas",
    city: "Cebu City",
    barangays: ["Lahug", "Apas"],
    streets: "Gorordo Ave, Salinas Drive portion, IT Park perimeter",
    reason: "Postponed following DPWH road schedule change. No brownout occurred.",
    fbCaption: "CANCELLATION: Maintenance scheduled along Gorordo Ave & Apas on Sep 2 is deferred until further notice. Power supply will continue without disruption.",
    fbTime: "Sep 2",
    isPast: true,
    outcome: "cancelled"
  },
  {
    fbPostId: "hist-sep01",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-09-01",
    dateLabel: "Sep 1, 2026",
    timeStart: "14:46",
    timeEnd: "16:50",
    time: "2:46 PM – 4:50 PM",
    type: "emergency",
    status: "restored",
    statusLabel: "Restored",
    area: "Basak San Nicolas & Mambaling",
    city: "Cebu City",
    barangays: ["Basak San Nicolas", "Mambaling"],
    streets: "N. Bacalso Ave, Tagunol St, C. Padilla St",
    reason: "Emergency recloser trip repaired by emergency troubleshooters.",
    fbCaption: "NORMALIZED: Recloser tripped along Basak San Nicolas and Mambaling has been repaired, tested, and normalized at 4:50 PM.",
    fbTime: "Sep 1",
    isPast: true,
    outcome: "restored"
  },
  {
    fbPostId: "hist-aug31",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-31",
    dateLabel: "Aug 31, 2026",
    timeStart: "08:30",
    timeEnd: "15:00",
    time: "8:30 AM – 3:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Pitogo, Lamac & Pulpogan",
    city: "Consolacion",
    barangays: ["Pitogo", "Lamac", "Pulpogan"],
    streets: "Consolacion Central Rd, Pitogo-Lamac Feeder Line",
    reason: "Replaced 12 aging wooden crossarms with galvanized steel arms.",
    fbCaption: "SERVICE ADVISORY COMPLETED: Line hardware modernization in Consolacion (Pitogo, Lamac, Pulpogan) finished on schedule. Power fully restored.",
    fbTime: "Aug 31",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug30",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-30",
    dateLabel: "Aug 30, 2026",
    timeStart: "09:00",
    timeEnd: "17:00",
    time: "9:00 AM – 5:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Tabunok & Bulacao",
    city: "Talisay City",
    barangays: ["Tabunok", "Bulacao"],
    streets: "San Isidro Road, Cebu South Road, Tabunok Public Market vicinity",
    reason: "Installed load break switch hardware across primary feeders.",
    fbCaption: "SCHEDULED MAINTENANCE COMPLETED: Service hardware installation concluded in Talisay. Normal power supply maintained.",
    fbTime: "Aug 30",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug29",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-29",
    dateLabel: "Aug 29, 2026",
    timeStart: "08:00",
    timeEnd: "16:30",
    time: "8:00 AM – 4:30 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Jubay & Catarman",
    city: "Liloan",
    barangays: ["Jubay", "Catarman"],
    streets: "Catarman Port Road, Jubay Coastal Highway",
    reason: "Primary line reconstruction and transformer load realignment.",
    fbCaption: "POWER RESTORATION: Scheduled maintenance in Liloan (Jubay and Catarman) has concluded safely. Power was re-energized at 4:30 PM.",
    fbTime: "Aug 29",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug28",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-28",
    dateLabel: "Aug 28, 2026",
    timeStart: "10:15",
    timeEnd: "12:45",
    time: "10:15 AM – 12:45 PM",
    type: "emergency",
    status: "restored",
    statusLabel: "Restored Early",
    area: "Banilad & Talamban",
    city: "Cebu City",
    barangays: ["Banilad", "Talamban"],
    streets: "Gov. M. Cuenco Ave, Maria Luisa Estate Park entrance",
    reason: "Overhead cable snagged by a high-cube container truck. Emergency repair completed.",
    fbCaption: "EMERGENCY POWER RESTORED: Lineworkers safely cleared damaged lines along Gov. Cuenco Ave in Banilad and restored electricity ahead of schedule.",
    fbTime: "Aug 28",
    isPast: true,
    outcome: "restored"
  },
  {
    fbPostId: "hist-aug27",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-27",
    dateLabel: "Aug 27, 2026",
    timeStart: "08:30",
    timeEnd: "17:00",
    time: "8:30 AM – 5:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Cabancalan & Bakilid",
    city: "Mandaue City",
    barangays: ["Cabancalan", "Bakilid"],
    streets: "M.L. Quezon National Hwy, Cabancalan Feeder line",
    reason: "Replacement of deteriorated high-voltage distribution insulators.",
    fbCaption: "MAINTENANCE COMPLETED: Scheduled system upgrading in Mandaue City concluded successfully at 5:00 PM.",
    fbTime: "Aug 27",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug26",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-26",
    dateLabel: "Aug 26, 2026",
    timeStart: "09:00",
    timeEnd: "16:00",
    time: "9:00 AM – 4:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Panadtaran & Pitalo",
    city: "San Fernando",
    barangays: ["Panadtaran", "Pitalo"],
    streets: "Cebu South Coastal Rd, South Poblacion feeder",
    reason: "Installation of concrete utility poles and relocation of low-hanging lines.",
    fbCaption: "SERVICE ADVISORY: San Fernando power improvement completed. All lines energized.",
    fbTime: "Aug 26",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug25",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-25",
    dateLabel: "Aug 25, 2026",
    timeStart: "13:00",
    timeEnd: "17:00",
    time: "1:00 PM – 5:00 PM",
    type: "cancelled",
    status: "cancelled",
    statusLabel: "Cancelled",
    area: "Tungkil & Tunghaan",
    city: "Minglanilla",
    barangays: ["Tungkil", "Tunghaan"],
    streets: "Tungkil Barangay Rd, Minglanilla South Hwy",
    reason: "Postponed due to thunderstorm warning issued by PAGASA. Supply remained ON.",
    fbCaption: "CANCELLATION ADVISORY: Scheduled maintenance in Minglanilla was cancelled for crew safety during adverse weather. Power was not interrupted.",
    fbTime: "Aug 25",
    isPast: true,
    outcome: "cancelled"
  },
  {
    fbPostId: "hist-aug24",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-24",
    dateLabel: "Aug 24, 2026",
    timeStart: "08:00",
    timeEnd: "16:00",
    time: "8:00 AM – 4:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Labangon & Tisa",
    city: "Cebu City",
    barangays: ["Labangon", "Tisa"],
    streets: "Katipunan St, F. Llamas St, Tisa Market junction",
    reason: "Upgraded capacity for distribution transformer bank serving residential feeders.",
    fbCaption: "SCHEDULED MAINTENANCE COMPLETED: Transformer upgrade in Labangon and Tisa concluded successfully.",
    fbTime: "Aug 24",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug23",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-23",
    dateLabel: "Aug 23, 2026",
    timeStart: "09:00",
    timeEnd: "15:00",
    time: "9:00 AM – 3:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Canduman & Cubacub",
    city: "Mandaue City",
    barangays: ["Canduman", "Cubacub"],
    streets: "Canduman-Talamban Road, Cubacub Proper",
    reason: "Overhead line reconnection and installation of surge arresters.",
    fbCaption: "MAINTENANCE COMPLETED: System modernization in Canduman and Cubacub has been successfully concluded.",
    fbTime: "Aug 23",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug22",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-22",
    dateLabel: "Aug 22, 2026",
    timeStart: "15:10",
    timeEnd: "17:30",
    time: "3:10 PM – 5:30 PM",
    type: "emergency",
    status: "restored",
    statusLabel: "Restored",
    area: "Tuyan & Inayagan",
    city: "City of Naga",
    barangays: ["Tuyan", "Inayagan"],
    streets: "Cebu South Road portion, Tuyan Elementary vicinity",
    reason: "Lightning strike on feeder line isolated and repaired by dispatch crew.",
    fbCaption: "EMERGENCY RESTORATION: Power successfully restored to Tuyan and Inayagan in City of Naga after lightning arrester replacement.",
    fbTime: "Aug 22",
    isPast: true,
    outcome: "restored"
  },
  {
    fbPostId: "hist-aug21",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-21",
    dateLabel: "Aug 21, 2026",
    timeStart: "08:30",
    timeEnd: "16:00",
    time: "8:30 AM – 4:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Nangka & Tolotolo",
    city: "Consolacion",
    barangays: ["Nangka", "Tolotolo"],
    streets: "Tolotolo Ridge Road, Nangka Valley Access",
    reason: "Reconstruction of overhead 13.8kV distribution wires to expand substation capacity.",
    fbCaption: "POWER RESTORATION: Consolacion service enhancement in Nangka and Tolotolo has concluded.",
    fbTime: "Aug 21",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug20",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-20",
    dateLabel: "Aug 20, 2026",
    timeStart: "09:00",
    timeEnd: "16:00",
    time: "9:00 AM – 4:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Cotcot & Calero",
    city: "Liloan",
    barangays: ["Cotcot", "Calero"],
    streets: "Cotcot Coastal Highway, Calero Bridge approach",
    reason: "Replacement of secondary cables and tensioning of primary feeders.",
    fbCaption: "SCHEDULED MAINTENANCE COMPLETED: Liloan linework completed successfully. Normal power supply has resumed.",
    fbTime: "Aug 20",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug19",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-19",
    dateLabel: "Aug 19, 2026",
    timeStart: "08:00",
    timeEnd: "17:00",
    time: "8:00 AM – 5:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Dumlog & Pooc",
    city: "Talisay City",
    barangays: ["Dumlog", "Pooc"],
    streets: "Pooc Barangay Road, Dumlog Seawall Drive",
    reason: "Installation of concrete spin poles to withstand coastal wind loads.",
    fbCaption: "MAINTENANCE COMPLETED: Talisay coastal feeder line enhancement completed at 5:00 PM.",
    fbTime: "Aug 19",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug18",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-18",
    dateLabel: "Aug 18, 2026",
    timeStart: "11:30",
    timeEnd: "14:15",
    time: "11:30 AM – 2:15 PM",
    type: "emergency",
    status: "restored",
    statusLabel: "Restored Early",
    area: "Punta Princesa & Quiot",
    city: "Cebu City",
    barangays: ["Punta Princesa", "Quiot"],
    streets: "F. Llamas Ext., Quiot Pardo Road",
    reason: "Faulty transformer bushing replaced swiftly by emergency standby squad.",
    fbCaption: "POWER RESTORATION: Emergency repairs at Punta Princesa and Quiot concluded earlier than estimated.",
    fbTime: "Aug 18",
    isPast: true,
    outcome: "restored"
  },
  {
    fbPostId: "hist-aug17",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-17",
    dateLabel: "Aug 17, 2026",
    timeStart: "08:30",
    timeEnd: "16:30",
    time: "8:30 AM – 4:30 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Paknaan & Tabok",
    city: "Mandaue City",
    barangays: ["Paknaan", "Tabok"],
    streets: "Plaridel St, UN Avenue intersection, Tabok Industrial Way",
    reason: "Elevating transmission cables over new flyover construction.",
    fbCaption: "SCHEDULED MAINTENANCE COMPLETED: UN Avenue line elevation completed safely.",
    fbTime: "Aug 17",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug16",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-16",
    dateLabel: "Aug 16, 2026",
    timeStart: "09:00",
    timeEnd: "15:00",
    time: "9:00 AM – 3:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Sangat & South Poblacion",
    city: "San Fernando",
    barangays: ["Sangat", "South Poblacion"],
    streets: "South National Highway, Sangat Shoreline Way",
    reason: "Upgrading feeder lines for San Fernando industrial port expansion.",
    fbCaption: "MAINTENANCE COMPLETED: San Fernando power grid improvement completed.",
    fbTime: "Aug 16",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug15",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-15",
    dateLabel: "Aug 15, 2026",
    timeStart: "08:00",
    timeEnd: "16:00",
    time: "8:00 AM – 4:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Cansaga & Tugbongan",
    city: "Consolacion",
    barangays: ["Cansaga", "Tugbongan"],
    streets: "Cansaga Riverbank Rd, Tugbongan Port Road",
    reason: "Reconductoring from bare conductors to tree-wire insulated conductors.",
    fbCaption: "SERVICE IMPROVEMENT COMPLETED: Insulated conductor conversion completed in Consolacion.",
    fbTime: "Aug 15",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug14",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-14",
    dateLabel: "Aug 14, 2026",
    timeStart: "13:00",
    timeEnd: "16:30",
    time: "1:00 PM – 4:30 PM",
    type: "scheduled",
    status: "restored",
    statusLabel: "Restored",
    area: "Lahug & Camputhaw",
    city: "Cebu City",
    barangays: ["Lahug", "Camputhaw"],
    streets: "Gorordo Ave, Escario St junction, JY Square vicinity",
    reason: "Substation load reconfiguration to reinforce IT Park power redundancy.",
    fbCaption: "ADVISORY: JY Square feeder maintenance completed. Power fully re-energized.",
    fbTime: "Aug 14",
    isPast: true,
    outcome: "restored"
  },
  {
    fbPostId: "hist-aug13",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-13",
    dateLabel: "Aug 13, 2026",
    timeStart: "08:30",
    timeEnd: "15:30",
    time: "8:30 AM – 3:30 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Linao & Mohon",
    city: "Talisay City",
    barangays: ["Linao", "Mohon"],
    streets: "Linao-Mohon Link Rd, Talisay City Hall vicinity",
    reason: "Installation of automated remote-controlled sectionalizer units.",
    fbCaption: "MAINTENANCE COMPLETED: Talisay line sectionalizer installation finished successfully.",
    fbTime: "Aug 13",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug12",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-12",
    dateLabel: "Aug 12, 2026",
    timeStart: "09:00",
    timeEnd: "16:00",
    time: "9:00 AM – 4:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Yati & Cabadiangan",
    city: "Liloan",
    barangays: ["Yati", "Cabadiangan"],
    streets: "Yati Central Highway, Cabadiangan Valley Road",
    reason: "Pole relocation and line clearance along widening project.",
    fbCaption: "POWER RESTORATION: Liloan road expansion utility relocation completed on time.",
    fbTime: "Aug 12",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug11",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-11",
    dateLabel: "Aug 11, 2026",
    timeStart: "10:00",
    timeEnd: "13:30",
    time: "10:00 AM – 1:30 PM",
    type: "emergency",
    status: "restored",
    statusLabel: "Restored Early",
    area: "Centro & Looc",
    city: "Mandaue City",
    barangays: ["Centro", "Looc"],
    streets: "A. Del Rosario St, Zamora St, Mandaue City Hall Plaza",
    reason: "Emergency replacement of blown transformer fuse cutout.",
    fbCaption: "EMERGENCY POWER RESTORED: Lineworkers safely replaced fuse cutout in Centro Mandaue.",
    fbTime: "Aug 11",
    isPast: true,
    outcome: "restored"
  },
  {
    fbPostId: "hist-aug10",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-10",
    dateLabel: "Aug 10, 2026",
    timeStart: "08:00",
    timeEnd: "16:00",
    time: "8:00 AM – 4:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Calajo-an & Tubod",
    city: "Minglanilla",
    barangays: ["Calajo-an", "Tubod"],
    streets: "South Coastal Expressway access, Tubod Hill Rd",
    reason: "Upgrading feeder lines and replacement of corroded crossarm brackets.",
    fbCaption: "MAINTENANCE COMPLETED: Minglanilla feeder maintenance finished successfully.",
    fbTime: "Aug 10",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug09",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-09",
    dateLabel: "Aug 9, 2026",
    timeStart: "09:00",
    timeEnd: "17:00",
    time: "9:00 AM – 5:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Poblacion Occidental & Jugan",
    city: "Consolacion",
    barangays: ["Poblacion Occidental", "Jugan"],
    streets: "Cebu North National Road, Consolacion Market perimeter",
    reason: "Installing secondary tie-lines to mitigate voltage fluctuations.",
    fbCaption: "SCHEDULED MAINTENANCE COMPLETED: Normal power resumed in Consolacion Poblacion and Jugan.",
    fbTime: "Aug 9",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug08",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-08",
    dateLabel: "Aug 8, 2026",
    timeStart: "13:00",
    timeEnd: "16:00",
    time: "1:00 PM – 4:00 PM",
    type: "cancelled",
    status: "cancelled",
    statusLabel: "Cancelled",
    area: "San Isidro & Lawaan",
    city: "Talisay City",
    barangays: ["San Isidro", "Lawaan I"],
    streets: "Lawaan Overpass vicinity, Rabaya St",
    reason: "Deferred due to high traffic volume on Cebu South Road. Power remained normal.",
    fbCaption: "CANCELLATION: Maintenance scheduled for Lawaan and San Isidro on Aug 8 deferred. Power remained ON.",
    fbTime: "Aug 8",
    isPast: true,
    outcome: "cancelled"
  },
  {
    fbPostId: "hist-aug07",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-07",
    dateLabel: "Aug 7, 2026",
    timeStart: "08:30",
    timeEnd: "16:30",
    time: "8:30 AM – 4:30 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Guadalupe & Capitol Site",
    city: "Cebu City",
    barangays: ["Guadalupe", "Capitol Site"],
    streets: "M. Velez St, B. Rodriguez St, Capitol Commercial area",
    reason: "Replacement of distribution poles and rerouting of feeder cables.",
    fbCaption: "SERVICE UPGRADE COMPLETED: Capitol Site and Guadalupe lines normalized at 4:30 PM.",
    fbTime: "Aug 7",
    isPast: true,
    outcome: "completed"
  },
  {
    fbPostId: "hist-aug06",
    fbPostUrl: "https://www.facebook.com/visayanelectriccompany",
    date: "2026-08-06",
    dateLabel: "Aug 6, 2026",
    timeStart: "09:00",
    timeEnd: "16:00",
    time: "9:00 AM – 4:00 PM",
    type: "scheduled",
    status: "completed",
    statusLabel: "Completed",
    area: "Poblacion & Cotcot",
    city: "Liloan",
    barangays: ["Poblacion", "Cotcot"],
    streets: "Liloan Lighthouse Road, Cotcot Port Access",
    reason: "Upgraded primary transformer bank and lightning shielding.",
    fbCaption: "SCHEDULED MAINTENANCE COMPLETED: Liloan Poblacion and Cotcot lines fully energized.",
    fbTime: "Aug 6",
    isPast: true,
    outcome: "completed"
  }
];

export async function runBackfill(): Promise<void> {
  console.log('Seeding / updating 30-day backfill data into SQLite (preserving existing data)...');
  let count = 0;
  for (let i = 0; i < THIRTY_DAY_DATA.length; i++) {
    const item = { ...THIRTY_DAY_DATA[i] };
    item.fbPostUrl = resolveRealFbPostUrl({
      fb_post_url: item.fbPostUrl,
      reason: item.reason,
      fb_caption: item.fbCaption,
      status: item.status,
      type: item.type,
    });
    item.fbImageUrl = item.fbImageUrl || REAL_FB_POSTS.DEFAULT_IMAGE;
    const live = computeLiveStatus(item);
    await insertOrUpdateInterruption({
      ...item,
      status: live.status,
      statusLabel: live.statusLabel,
      isPast: live.isPast,
    });
    count++;
  }

  console.log(`Reconciling interruptions to apply area-specific superseding...`);
  const stats = await reconcileAllInterruptions();
  console.log(`Reconciliation complete: ${stats.activeCount} active, ${stats.supersededCount} superseded, ${stats.trimmedCount} trimmed.`);

  await logScrapeRun({
    durationMs: 480,
    postsFound: count,
    newAdvisories: count,
    status: 'success',
  });
  
  console.log(`Successfully seeded ${count} advisories covering 30 days into SQLite.`);
}

if (require.main === module) {
  runBackfill().then(() => process.exit(0)).catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
